# Generated by Django 5.2.10 on 2026-01-18 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PLEDGED', 'Pledged'), ('PAID', 'Paid'), ('RETURNED', 'Returned'), ('DEFAULT_COVERED', 'Default covered')], default='PLEDGED', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=20)),
                ('provider_session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='campaigns.campaign')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('DEFAULT_COVER', 'Default cover'), ('RETURN', 'Return')], max_length=20)),
                ('amount_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_borrow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='borrow.borrowrequest')),
                ('related_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='campaigns.campaign')),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.contribution')),
            ],
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='payments_co_status_97f737_idx'),
        ),
        migrations.AddIndex(
            model_name='platformledger',
            index=models.Index(fields=['type'], name='payments_pl_type_36b5f6_idx'),
        ),
    ]
