# Generated by Django 5.2.10 on 2026-01-18 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=20)),
                ('provider_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_payments', to='borrow.borrowrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='repayments__status_e6b4f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RepaymentScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('LATE', 'Late'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='borrow.borrowrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='repayments__status_dcaf49_idx')],
            },
        ),
    ]
