# Generated by Django 5.2.10 on 2026-01-18 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
        ('repayments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], max_length=20)),
                ('provider_session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_setups', to='borrow.borrowrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_setups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
