# Generated by Django 5.2.10 on 2026-01-18 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('reason_detailed', models.TextField()),
                ('amount_requested_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('expected_return_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CAMPAIGN_CREATED', 'Campaign created'), ('FUNDED', 'Funded'), ('DISBURSED', 'Disbursed'), ('IN_REPAYMENT', 'In repayment'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30)),
                ('admin_note_internal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('UPLOADED', 'Uploaded'), ('CONFIRMED', 'Confirmed')], default='PENDING_UPLOAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='borrow.borrowrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status'], name='borrow_borr_status_2376e4_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowdocument',
            index=models.Index(fields=['status'], name='borrow_borr_status_64953c_idx'),
        ),
    ]
