# Generated by Django 5.2.10 on 2026-01-18 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_public', models.CharField(max_length=255)),
                ('story_public', models.TextField()),
                ('terms_public', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('amount_needed_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_pooled_cents', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_return_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('FUNDED', 'Funded'), ('DISBURSED', 'Disbursed'), ('IN_REPAYMENT', 'In repayment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrow_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to='borrow.borrowrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='campaigns_c_status_96cb56_idx')],
            },
        ),
    ]
